apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-warehouse
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: service-warehouse
  template:
    metadata:
      labels:
        app: service-warehouse
    spec:
      containers:
      - name: service-warehouse
        image: "{{ .Values.image.repository }}:{{ .Values.image.tags.service_warehouse }}"
        imagePullPolicy: Always
        env:
        - name: SERVICE_NAME      # Определяем, какой сервис запустить
          value: "service-warehouse"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5  # Задержка перед первым запуском проверки
          periodSeconds: 10       # Как часто выполнять проверку
          timeoutSeconds: 5       # Максимальное время ожидания ответа на запрос
          failureThreshold: 3     # Количество неудачных попыток, прежде чем контейнер будет перезапущен
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10 # Задержка перед первым запуском проверки
          periodSeconds: 10       # Как часто выполнять проверку
          timeoutSeconds: 5       # Максимальное время ожидания ответа на запрос
          failureThreshold: 3     # Количество неудачных попыток, прежде чем контейнер будет исключен из списка доступных
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}-secrets