controller:
  service:
    type: NodePort

  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
    service:
      port: 10254
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"

  extraArgs:
    metrics-per-host: "true"