apiVersion: v1
kind: Service
metadata:
  name: metrics-api-php-app
  labels:
    app: metrics-api-php-app
spec:
  selector:
    app: php-app  # Должен совпадать с лейблами пода
  ports:
    - protocol: TCP
      port: 80  # Порт сервиса
      targetPort: 80  # Порт пода, где слушает экспортер