apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.db_config }}
  {{ $key }}: {{ $value | toString | b64enc }}
  {{- end }}
  db_password: {{ .Values.db_password | toString | b64enc }}