apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: user-service-metrics-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
#        livenessProbe:
#          httpGet:
#            path: /health
#            port: 80
#          initialDelaySeconds: 10  # Задержка перед первым запуском проверки
#          periodSeconds: 10       # Как часто выполнять проверку
#          timeoutSeconds: 5       # Максимальное время ожидания ответа на запрос
#          failureThreshold: 3     # Количество неудачных попыток, прежде чем контейнер будет перезапущен
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10  # Задержка перед первым запуском проверки
          periodSeconds: 10       # Как часто выполнять проверку
          timeoutSeconds: 5       # Максимальное время ожидания ответа на запрос
          failureThreshold: 3     # Количество неудачных попыток, прежде чем контейнер будет исключен из списка доступных
        envFrom:
        - secretRef:
           name: {{ .Release.Name }}-secrets
        env:
        - name: TEST
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: TEST