{
 "title": "arch.homework | Metrics",
 "description": "API and Nginx Ingress Metrics Dashboard",
 "tags": [
  "api",
  "nginx",
  "monitoring"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "API Latency (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\"}[2m])))",
     "legendFormat": "/user - max"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\"}[2m])))",
     "legendFormat": "/user - 0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\"}[2m])))",
     "legendFormat": "/user - 0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\"}[2m])))",
     "legendFormat": "/user - 0.5"
    }
   ]
  },
  {
   "title": "Nginx Ingress Latency (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"ingress-nginx\", job=\"ingress-nginx-metrics\"}[2m])))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"ingress-nginx\", job=\"ingress-nginx-metrics\"}[2m])))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"ingress-nginx\", job=\"ingress-nginx-metrics\"}[2m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"ingress-nginx\", job=\"ingress-nginx-metrics\"}[2m])))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "API Error Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "(sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\", status=~\"5..\", method=\"GET\"}[2m])) / sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\"}[2m]))) * 100",
     "legendFormat": "/user - GET - 5xx"
    },
    {
     "expr": "(sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\", status=~\"5..\", method=\"PUT\"}[2m])) / sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\"}[2m]))) * 100",
     "legendFormat": "/user - PUT - 5xx"
    },
    {
     "expr": "(sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\", status=~\"5..\", method=\"DELETE\"}[2m])) / sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\"}[2m]))) * 100",
     "legendFormat": "/user - DELETE - 5xx"
    }
   ]
  },
  {
   "title": "Nginx Ingress Error Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "(sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", status=~\"5..\"}[2m])) / sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\"}[2m]))) * 100",
     "legendFormat": "5xx"
    },
    {
     "expr": "(sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", status=~\"2..\"}[2m])) / sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\"}[2m]))) * 100",
     "legendFormat": "2xx"
    }
   ]
  },
  {
   "title": "API RPS (requests per seconds)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\", method=\"POST\"}[2m]))",
     "legendFormat": "/user - POST"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\", method=\"GET\"}[2m]))",
     "legendFormat": "/user - GET"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\", method=\"PUT\"}[2m]))",
     "legendFormat": "/user - PUT"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\", method=\"DELETE\"}[2m]))",
     "legendFormat": "/user - DELETE"
    }
   ]
  },
  {
   "title": "Nginx Ingress RPS (requests per seconds)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\"}[2m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  { "title": "CPU & Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Pods CPS",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"php-app.*\"}[2m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Pods Memory (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_memory_working_set_bytes{namespace=\"default\", pod=~\"php-app.*\"}[2m])) / 1024 / 1024",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}