{
 "title": "arch.homework | Metrics",
 "description": "API and Nginx Ingress Metrics Dashboard",
 "tags": [
  "api",
  "nginx",
  "monitoring",
  "postgresql",
  "redis"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(up{job=~\"postgres.*\"},instance)"
    }
   },
   {
    "name": "db",
    "label": "db",
    "query": {
     "query": "label_values({\"pg_stat_database_tup_fetched\t\", instance=~\"$host\", datname!~\"template.*|postgres\"},datname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "API & Nginx Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Latency (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\"}[2m])))",
     "legendFormat": "/user - max"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\"}[2m])))",
     "legendFormat": "/user - 0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\"}[2m])))",
     "legendFormat": "/user - 0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\"}[2m])))",
     "legendFormat": "/user - 0.5"
    }
   ]
  },
  {
   "title": "Nginx Ingress Latency (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"ingress-nginx\", job=\"ingress-nginx-metrics\"}[2m])))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"ingress-nginx\", job=\"ingress-nginx-metrics\"}[2m])))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"ingress-nginx\", job=\"ingress-nginx-metrics\"}[2m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"ingress-nginx\", job=\"ingress-nginx-metrics\"}[2m])))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "API Error Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "(sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\", status=~\"5..\", method=\"GET\"}[2m])) / sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\"}[2m]))) * 100",
     "legendFormat": "/user - GET - 5xx"
    },
    {
     "expr": "(sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\", status=~\"5..\", method=\"PUT\"}[2m])) / sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\"}[2m]))) * 100",
     "legendFormat": "/user - PUT - 5xx"
    },
    {
     "expr": "(sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\", status=~\"5..\", method=\"DELETE\"}[2m])) / sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\"}[2m]))) * 100",
     "legendFormat": "/user - DELETE - 5xx"
    }
   ]
  },
  {
   "title": "Nginx Ingress Error Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "(sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", status=~\"5..\"}[2m])) / sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\"}[2m]))) * 100",
     "legendFormat": "5xx"
    },
    {
     "expr": "(sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", status=~\"2..\"}[2m])) / sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\"}[2m]))) * 100",
     "legendFormat": "2xx"
    }
   ]
  },
  {
   "title": "API RPS (requests per seconds)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\", method=\"POST\"}[2m]))",
     "legendFormat": "/user - POST"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\", method=\"GET\"}[2m]))",
     "legendFormat": "/user - GET"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\", method=\"PUT\"}[2m]))",
     "legendFormat": "/user - PUT"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\", path=\"/user\", method=\"DELETE\"}[2m]))",
     "legendFormat": "/user - DELETE"
    }
   ]
  },
  {
   "title": "Nginx Ingress RPS (requests per seconds)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"ingress-nginx\", service=\"php-app\", namespace=\"default\", job=\"ingress-nginx-metrics\"}[2m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  { "title": "CPU & Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Pods CPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"php-app.*\"}[2m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Pods Memory (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_memory_working_set_bytes{namespace=\"default\", pod=~\"php-app.*\"}[2m])) / 1024 / 1024",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Redis Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "command": "info", "section": "server", "streamingCapacity": 1, "type": "command" }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "command": "info", "section": "server", "streamingCapacity": 1, "type": "command" }
   ]
  },
  { "title": "Postgesql", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Conflicts/Deadlocks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "conflicts",
     "expr": "sum(rate(pg_stat_database_deadlocks{datname=~\"$db\",instance=~\"$host\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "deadlocks",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "deadlocks",
     "expr": "sum(rate(pg_stat_database_conflicts{datname=~\"$db\",instance=~\"$host\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "conflicts",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "deadlocks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Rows",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_fetched{datname=~\"$db\",instance=~\"$host\"}[2m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "fetched",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_returned{datname=~\"$db\",instance=~\"$host\"}[2m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "returned",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_inserted{datname=~\"$db\",instance=~\"$host\"}[2m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "inserted",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_updated{datname=~\"$db\",instance=~\"$host\"}[2m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "updated",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_deleted{datname=~\"$db\",instance=~\"$host\"}[2m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "deleted",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_tup_fetched{datname=~\"$db\",instance=~\"$host\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}