[supervisord]
nodaemon=true

[program:nginx]
command=nginx -g "daemon off;"

[program:php-fpm]
command=php-fpm

[program:nginx-exporter]
command=/usr/local/bin/nginx-prometheus-exporter -nginx.scrape-uri http://localhost:80/nginx_status