apiVersion: v1
kind: Service
metadata:
  name: metrics-nginx-exporter-php-app
  labels:
    app: metrics-nginx-exporter-php-app
spec:
  selector:
    app: php-app  # Должен совпадать с лейблами пода
  ports:
    - protocol: TCP
      port: 9113  # Порт сервиса
      targetPort: 9113  # Порт пода, где слушает экспортер