apiVersion: v1
kind: Service
metadata:
  name: metrics-nginx-exporter-service-order
  labels:
    app: metrics-nginx-exporter-service-order
spec:
  selector:
    app: service-order  # Должен совпадать с лейблами пода
  ports:
    - protocol: TCP
      port: 9113  # Порт сервиса
      targetPort: 9113  # Порт пода, где слушает экспортер