apiVersion: v1
kind: ConfigMap
metadata:
  name: config-camel
data:
  application.properties: |
    camel.routes.rabbitmq-to-http.from=rabbitmq:my-exchange?queue=my-queue&autoDelete=false
    camel.routes.rabbitmq-to-http.to=http://arch.homework/rabbitmq-test
    camel.routes.rabbitmq-to-http.log=Message received from RabbitMQ: ${body}
    spring.rabbitmq.host=rabbitmq
    spring.rabbitmq.port=5672
    spring.rabbitmq.username=nauths
    spring.rabbitmq.password=WQEAsdaewa