{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: php-app
            port:
              number: 80
      - path: /health
        pathType: Exact
        backend:
          service:
            name: php-app
            port:
              number: 80
      - path: /user
        pathType: Prefix
        backend:
          service:
            name: php-app
            port:
              number: 80
      - path: /api_metrics
        pathType: Exact
        backend:
          service:
            name: php-app
            port:
              number: 80
#spec:
#  ingressClassName: nginx
#  rules:
#  - http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: php-app
#            port:
#              number: 80
{{- end }}