apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter-metrics
  labels:
    app: nginx-exporter-metrics
spec:
  selector:
    app: php-app  # Должен совпадать с лейблами пода
  ports:
    - protocol: TCP
      port: 9113  # Порт сервиса
      targetPort: 9113  # Порт пода, где слушает экспортер