apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.db_config }}
  {{ $key }}: {{ $value | toString | b64enc }}
  {{- end }}
#  db_password: {{ .Values.secrets.db_config.db_password | toString | b64enc }}
#  POSTGRES_PASSWORD: {{ .Values.secrets.db_config.POSTGRES_PASSWORD | toString | b64enc }}